### PR TITLE
Export uri_decode and improve performance

### PR DESCRIPTION
**Pull request by pichi**
Implementation of uri_decode has O(N^2) time complexity. New implementation has O(N). Using `binary_to_integer/2` doesn't show any performance improvement to the alternative code is useless. Using selective `inline` compile directive has a much bigger effect. Exporting this function allows decode request Path which is not decoded by default.

### CODE REVIEW

**Comment by yurrriq** [comment]
Thanks! This looks good to me. Any objections, @elli-lib/team?

**Review by yurrriq — APPROVED** [review]

**Comment by deadtrickster** [comment]
how it compares to http://erlang.org/doc/man/http_uri.html?

**Comment by yurrriq** [comment]
@deadtrickster: https://github.com/elli-lib/elli/commit/e94b2fc4a9d5af45fb1df57406c1519aa489cf7d

**Comment by yurrriq** [comment]
This LGTM. Will merge tomorrow, unless someone objects.

**Pull request merged**
