### PR TITLE
include req_body size in sizes list

### PR DESCRIPTION
**Pull request by tsloughter**

### CODE REVIEW

**Comment by deadtrickster** [comment]
maybe not relevant but how ContentLength et al work with chuncked requests?

**Comment by tsloughter** [comment]
If there is one it should be ignored. Right now this won't get a size for a chunked request. You have to use a `handover` elli handler for it as well anyway, right? So there would need to be a way for the handler to record sizes.

**Review by yurrriq — APPROVED** [review]
I'd love to have a test for this too, but we can always and one or more later.

**Comment by tsloughter** [comment]
Ah yea, good point, I'll add a test after Infinity War :)

**Comment by yurrriq** [comment]
Sounds good to me. Enjoy! It was one of the least worst (loose) screen adaptations of a comic (universe) I've seen in a while. :smile:

**Pull request merged**
