### PR TITLE
Request start timing fix

### LINKED ISSUE #19: Request durations too large
I'm seeing request durations (request_end - request_start) of multiple seconds for sub-second page refreshes in browsers, but not curl.

That metric seemed like best measure of true response time (as noted in original elli sources).

What is going on?

Here's the prometheus.erl code:

```
handle_event(request_complete,
             [Req, ResponseCode, _ResponseHeaders, _ResponseBody,
              {Timings, _Sizes}],
             _Config) ->
    prometheus_counter:inc(http_requests_total,
                           [ResponseCode, rawpath(Req)]),
    Start = proplists:get_value(request_start, Timings),
    End = proplists:get_value(request_end, Timings),
    NativeDelta = End - Start,
    io:format("handle_event: ~p  ~p  ~p~n",
              [ResponseCode,
               erlang:convert_time_unit(NativeDelta, native, micro_seconds),
               rawpath(Req)]),
    prometheus_histogram:observe(response_time_in_microseconds,
                                 [rawpath(Req)], NativeDelta),
    ok;
```

the Erlang interpreter output:

```
handle_event: 200  1990847  <<"/hello/world">>
handle_event: 200  2740893  <<"/metrics">>
handle_event: 200  1239785  <<"/metrics">>
handle_event: 200  2138739  <<"/hello/world">>
```

and if I use curl instead, I get output like this:

```
handle_event: 200  1409  <<"/hello/world">>
handle_event: 200  112  <<"/hello/world">>
handle_event: 404  100  <<"/hmetrics">>
handle_event: 200  6334  <<"/metrics">>
handle_event: 200  6614  <<"/metrics">>
```

Chrome also is high:

```
handle_event: 200  183414  <<"/hello/world">>
handle_event: 404  350253  <<"/favicon.ico">>
handle_event: 200  7395448  <<"/metrics">>
handle_event: 200  3918845  <<"/metrics">>
handle_event: 200  1744633  <<"/metrics">>
```

### PR DESCRIPTION
**Pull request by deadtrickster**
fixes #19

I've used hackney for keep-alive test.

cc @mbucc

### CODE REVIEW

**Comment by yurrriq** [comment]
https://travis-ci.org/elli-lib/elli/jobs/179183371#L323

**Comment by deadtrickster** [comment]
Yeah. Timing error.  Restarted

**Comment by deadtrickster** [comment]
Very inconsistent Travis performance today

**Comment by yurrriq** [comment]
Looks green now. Can/should we convert all the request tests to use hackney? Maybe that's out of scope here. This looks good to merge, I think. Go ahead if you agree.

**Comment by deadtrickster** [comment]
Yeah, I'd be surprised if httpc doesn't support keep-alive. But I wasn't able to find something :-(.

To me this looks good and I'll merge.

**Comment by yurrriq** [comment]
I'm not sure I follow. I was just thinking for the sake of continuity, it'd be nice to have one way of writing request tests.

**Pull request merged**
