### PR TITLE
Added scheme, host and port to #req in mk_req

### PR DESCRIPTION
**Pull request by CharlesOkwuagwu**

### CODE REVIEW

**Comment by yurrriq** [comment]
Thanks for getting this started. @deadtrickster will work on fixing the build. We need to be sure to bump the version accordingly, since we're breaking `#req{}`.

**Comment by deadtrickster** [comment]
Ok, so first of all. This broke dialyzer. Secondly - as always here is RFC section - https://tools.ietf.org/html/rfc7230#section-5.3. And we need a little bit more code here. Too bad github doesn't have reminders. But I will look into that.

**Comment by tsloughter** [comment]
@yurrriq oh I see what happened :).

@deadtrickster what are you saying about request target?

**Comment by deadtrickster** [comment]
@tsloughter what is 'request target'? =)

**Comment by tsloughter** [comment]
@deadtrickster that is the section of the rfc you linked to.

**Comment by deadtrickster** [comment]
I think I meant that target has different formats. Not each request comes with host for example. But I don't remember now

**Comment by tsloughter** [comment]
Hm, I thought I commented on this yesterday.

Can we get this merged? I need it for opencensus attributes support :)

**Comment by fenollp** [comment]
You actually did! Past day has been rough on github...

**Comment by yurrriq** [comment]
I’ll work on polishing this tonight or over the weekend.

**Comment by yurrriq** [comment]
being replaced by #46

**Pull request closed without merging**
