### PR TITLE
Tls sendfile

### PR DESCRIPTION
**Pull request by deadtrickster**
replacing #23.

### CODE REVIEW

**Comment by deadtrickster** [comment]
So what's going on here? I forgot😂

**Comment by Vagabond** [comment]
ping?

**Comment by yurrriq** [comment]
What's up with this?

**Review by tsloughter — APPROVED** [review]

**Comment by tsloughter** [comment]
I think this should be merged once the test is fixed.

**Comment by yurrriq** [comment]
Superseded by #48.
Published https://hex.pm/packages/elli/2.1.2

**Pull request closed without merging**
