### PR TITLE
Fix spec for elli:stop/1

### LINKED ISSUE #111: Invalid spec for elli:stop/1
The current spec is:

```
%% @doc Stop `Server'.
-spec stop(Server :: atom()) -> {stop, normal, ok, state()}.
stop(S) ->
    gen_server:call(S, stop).
```

Shouldn't it be just:
```
-spec stop(Server :: atom() | pid()) -> ok.
```

### PR DESCRIPTION
**Pull request by paulo-ferraz-oliveira**
Closes #111.

Depends on the CI file updates from #114, so shall be rebased and updated (if required) after that one.

### CODE REVIEW

**Comment by paulo-ferraz-oliveira** [comment]
Tests will most likely fail because `ubuntu-latest` moved from `ubuntu-20.04` to `ubuntu-22.04`. Merging https://github.com/elli-lib/elli/pull/112, then rebasing, should fix it (or I can do the same fix here).

**Comment by paulo-ferraz-oliveira** [comment]
~CI failing for OTP 26, and 25. I'll try to replicate locally.~

**Comment by paulo-ferraz-oliveira** [comment]
~It's possible the failure for non-OTP 26 is due to #99, since re-executing the tests (in a fork) showed ✅.~

**Comment by paulo-ferraz-oliveira** [comment]
~Removed OTP 26 from scope, since there're SSL -related issues to solve. Should be moved to a new PR, I guess...~

**Comment by paulo-ferraz-oliveira** [comment]
Is anything lacking for this one to get merged? I can then rebase and update the other ones.

**Comment by paulo-ferraz-oliveira** [comment]
Moved to draft. These don't need to be reviewed before #114, after which I'll rebase.

**Comment by paulo-ferraz-oliveira** [comment]
@tsloughter

**Review by tsloughter — APPROVED** [review]

**Pull request merged**
