### PR TITLE
master/develop branch sync.

### PR DESCRIPTION
**Pull request by paulo-ferraz-oliveira**
This Pull Request is a cherry-pick -based collection of the diff. between branches `master` and `develop`, so that `develop` can be deleted (thus `master` becoming the default), as proposed by [@tsloughter on 25.May.20](https://github.com/elli-lib/elli/issues/86#issuecomment-633720221).

### CODE REVIEW

**Comment by paulo-ferraz-oliveira** [comment]
This also means that the open Pull Request might have to be rebased, since they all propose merging into `develop`.

**Comment by tsloughter** [comment]
I wouldn't bother with this. I figure if we are renaming the default branch it might as well be `main` and so it can just be pushed as a new branch from develop directly.

**Comment by paulo-ferraz-oliveira** [comment]
Sure. In any case, do you think it appropriate to create a release soonish? You can reply and close the PR, if that's OK.

**Comment by paulo-ferraz-oliveira** [comment]
It closed by itself, since I deleted the ref. branch. Oh, well...

**Comment by tsloughter** [comment]
@paulo-ferraz-oliveira I have a release ready. I just wanted to wait for one of the other maintainers to sign off on it before I merged and published. But I haven't been able to get in contact with them.

**Pull request closed without merging**
