### PR TITLE
Update minimum required OTP version in the README

### PR DESCRIPTION
**Pull request by deadtrickster**

### CODE REVIEW

**Comment by yurrriq** [comment]
Does 18.0 work too?

**Comment by deadtrickster** [comment]
I guess so, but haven't tested since I just don't have this verson (only 19)

quote from the docs (http://erlang.org/doc/apps/erts/time_correction.html):

```
As of OTP 18 (ERTS version 7.0) the time functionality of Erlang has been extended. This includes a new API for time and time warp modes that alter the system behavior when system time changes
```

**Comment by yurrriq** [comment]
Maybe we should have Travis try it.

**Comment by yurrriq** [comment]
Maybe we should have Travis try it.

**Comment by yurrriq** [comment]
It does indeed work on 18.0 and I've updated the README accordingly in 87061ce4691d44c282c14a3367d843050bb26c46.

**Pull request closed without merging**
