### PR TITLE
Add TLS implementation for sendfile

### PR DESCRIPTION
**Pull request by deadtrickster**
The implementation is taken from Ranch PR #41 by fishcakes, with
permission.

cc @Vagabond

### CODE REVIEW

**Comment by yurrriq** [comment]
We need to appease Elvis [here](https://travis-ci.org/elli-lib/elli/jobs/187036051#L292-L296).

**Comment by deadtrickster** [comment]
I'm merging it to tls-sendfile branch. @Vagabond if you have objections regarding copyright or something please let us now. In the meantime I'll review the code, Elvis, etc.

**Comment by Vagabond** [comment]
I was actually going to integrate the accompanying test suite as well, but I ran out of time.

**Comment by deadtrickster** [comment]
@Vagabond in #25 I added a simple sendfile test (actually just  a copy-paste from non-tls tests). If you already have more tests (ranges probably?) could you please just push them somewhere?
Or if you don't feel like doing this, could you please tell me what test scenarios you had.

**Comment by Vagabond** [comment]
https://github.com/fishcakez/ranch/blob/ca6817880ee5592cf890fb5a71da41f52818d29a/test/sendfile_SUITE.erl

I was going to adapt this test suite to elli.

**Pull request merged**
